<a href="https://colab.research.google.com/github/Olleum/-BI--Yandex-DataLens-/blob/main/Laba2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
matrix = []
n = int(input("Введите n: "))

for i in range(n):
    matrix.append([])
    print(f"Введите элементы для строки {i+1}:")
    for j in range(n + 1):
        element = float(input())
        matrix[i].append(element)


Введите n: 4
Введите элементы для строки 1:
24
2
4
-9
-9
Введите элементы для строки 2:
-6
-27
-8
-6
-76
Введите элементы для строки 3:
-4
8
19
6
-79
Введите элементы для строки 4:
4
5
-3
-13
-70


In [5]:
A = []
b = []

for i in range(n):
    A.append(matrix[i][:n])  # первые n элементов
    b.append(matrix[i][n])  # последний элемент

import numpy as np
A = np.array(A)
b = np.array(b)

print("Матрица A:")
print(A)

print("Вектор b:")
print(b)

Матрица A:
[[ 24.   2.   4.  -9.]
 [ -6. -27.  -8.  -6.]
 [ -4.   8.  19.   6.]
 [  4.   5.  -3. -13.]]
Вектор b:
[ -9. -76. -79. -70.]


In [6]:
eps = float(input("Введите точность (например 0.001): "))

x = np.zeros(n)
k = 0

while True:
    x_new = np.zeros(n)

    for i in range(n):
        s = 0
        for j in range(n):
            if j != i:
                s += A[i][j] * x[j]

        x_new[i] = (b[i] - s) / A[i][i]

    if np.max(np.abs(x_new - x)) < eps:
        break

    x = x_new.copy()
    k += 1

print("\nРешение (простая итерация):")
for i in range(n):
    print(f"x{i+1} = {round(x_new[i], 5)}")

print("Количество итераций:", k)

Введите точность (например 0.001): 0.1

Решение (простая итерация):
x1 = 4.05961
x2 = 1.97693
x3 = -7.01681
x4 = 9.04231
Количество итераций: 6


In [7]:
x = np.zeros(n)
k = 0

while True:
    x_new = x.copy()

    for i in range(n):
        s1 = 0
        s2 = 0

        for j in range(i):
            s1 += A[i][j] * x_new[j]

        for j in range(i + 1, n):
            s2 += A[i][j] * x[j]

        x_new[i] = (b[i] - s1 - s2) / A[i][i]

    if np.max(np.abs(x_new - x)) < eps:
        break

    x = x_new.copy()
    k += 1

print("\nРешение (Зейдель):")
for i in range(n):
    print(f"x{i+1} = {round(x_new[i], 5)}")

print("Количество итераций:", k)


Решение (Зейдель):
x1 = 3.99481
x2 = 2.00096
x3 = -6.9984
x4 = 8.9984
Количество итераций: 4


In [8]:
print("\nПРОВЕРКА:")

for i in range(n):
    left = 0

    for j in range(n):
        left += A[i][j] * x_new[j]

    print(f"Уравнение {i+1}: {round(left,4)} = {b[i]}")


ПРОВЕРКА:
Уравнение 1: -9.1019 = -9.0
Уравнение 2: -75.9979 = -76.0
Уравнение 3: -78.9508 = -79.0
Уравнение 4: -70.0 = -70.0
